const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const context = { window: {}, localStorage: { getItem: () => null, setItem: () => {}, removeItem: () => {} } };
vm.createContext(context);
for (const file of ['data/rutgers_team.js','data/rutgers_playbook.js','data/weekly_plan.js','data/game_history.js','data/recruiting_data.js','data/engine_data.js']) {
  vm.runInContext(fs.readFileSync(path.join(root, file), 'utf8'), context, { filename: file });
}
Object.assign(global, context.window);
global.window = { GAME_HISTORY: [] };
global.localStorage = context.localStorage;
const engine = require(path.join(root, 'app.js'));
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const checks = [];
function check(name, passed, detail = '') { checks.push({ name, passed: Boolean(passed), detail }); }
function ctx(down, yards, zone = 'normal', gameState = 'normal') {
  const dist = yards <= 3 ? 'short' : yards <= 6 ? 'medium' : 'long';
  let key = dist;
  if (zone === 'goal_line' || zone === 'red_zone') key = zone;
  if (gameState === 'two_minute' || gameState === 'must_score') key = gameState;
  if (gameState === 'protect_lead') key = 'short';
  return { down, dist, distanceYards: yards, zone, gameState, key };
}
const requiredFiles = ['rutgers_roster_base.json','recruiting_class.json','recruiting_weekly.json','team_needs.json','coach_recruiting_modifiers.json','purdue_opponent_profile.json','purdue_opponent_players.json','purdue_opponent_position_groups.json','purdue_matchups.json','gameplan_weekly.json','APP_DATA_BINDING_REQUIREMENTS.json'];
check('Authoritative enriched JSON files are present', requiredFiles.every(file => fs.existsSync(path.join(root,'data',file))));
check('Shared roster source has 48 verified players', RUTGERS_ROSTER_BASE.players.length === 48 && RUTGERS_ROSTER_BASE.package_type === 'rutgers_roster_base');
check('No duplicate hardcoded roster is used by the visible Recruiting engine', app.includes('function loadRutgersRoster') && app.includes('return sharedRosterBase()'));
check('Gameplan engine reads enriched opponent/profile/player/group/matchup data', app.includes('loadOpponentProfile') && app.includes('loadOpponentPlayers') && app.includes('loadOpponentGroups') && app.includes('loadMatchups'));
check('Recruiting engine reads enriched class, weekly, team needs, and coach modifiers', app.includes('loadRecruitingClass') && app.includes('loadRecruitingWeekly') && app.includes('loadTeamNeeds') && app.includes('COACH_RECRUITING_MODIFIERS'));
check('Gameplan tab structure is present', ['gameMatchupHeader','recommendation','top3Inline','quickSummary','gameDayUsage','gameDayAlerts'].every(token => app.includes(token) || index.includes(token)));
check('Best Call keeps visible play art', app.includes('large-diagram') && app.includes('play.diagramPath'));
check('Top Plays supports required filters', ['run','pass','rpo','pa','screen','rankFormation','rankPersonnel','rankSituation','rankRisk','rankZone','rankState'].every(token => app.includes(token)));
check('Personnel heading and dynamic Rutgers/opponent comparison exist', app.includes('Personnel & Matchups') && app.includes('renderGameMatchupHeader') && app.includes('activeOpponentName()'));
check('Personnel includes run direction map', app.includes('function renderRunDirection') && app.includes('lane-map') && app.includes('Left edge') && app.includes('Right edge'));
check('Run direction map avoids horizontal overflow at phone width', css.includes('grid-template-columns:repeat(auto-fit,minmax(92px,1fr))') && css.includes('overflow-x:hidden'));
check('Personnel includes protection map', app.includes('function renderProtection') && app.includes('pressure-map') && app.includes('Right edge') && app.includes('highestRiskMatchup'));
check('Protection map avoids horizontal overflow at phone width', css.includes('grid-template-columns:repeat(auto-fit,minmax(104px,1fr))'));
check('Personnel includes current opponent cards', app.includes('function renderOpponent') && app.includes('${activeOpponentName()} Players') && PURDUE_OPPONENT_PLAYERS.players.length === 16);
check('Personnel includes matchup cards', app.includes('function renderMatchups') && PURDUE_MATCHUPS.matchups.length >= 3);
check('Recruiting overview uses real resources', RECRUITING_WEEKLY.resources.scholarship_limit === 35 && RECRUITING_WEEKLY.resources.weekly_hours_total === 440 && app.includes('scholarships_used'));
check('All recruiting positions are filterable from class data', new Set(RECRUITING_CLASS.prospects.map(p => p.position).filter(Boolean)).size >= 10 && app.includes('filterPosition'));
check('Prospect descriptions display from analysis', RECRUITING_CLASS.prospects.every(p => p.analysis && p.analysis.summary) && app.includes('Scouting summary'));
check('Opponent player descriptions display from ui_analysis', PURDUE_OPPONENT_PLAYERS.players.every(p => p.ui_analysis && p.ui_analysis.summary) && app.includes('ui_analysis'));
check('Matchup descriptions display', PURDUE_MATCHUPS.matchups.every(m => m.description) && app.includes('row.description'));
check('Null fields are hidden in normal UI helpers', app.includes('function maybeRow') && app.includes('return cleaned ?') && !app.includes('Unknown stars'));
check('No Name unverified remains', !index.includes('Name unverified') && !app.includes('Name unverified'));
check('No static opponent facts remain in noscript fallback', !index.includes('Purdue record') && !index.includes('Q. Gillians') && index.includes('Enable JavaScript'));
check('No old four quarterback summary boxes remain', !app.includes('Quarterbacks') || app.indexOf('Quarterbacks') < app.indexOf('function loadRutgersRoster'));
check('No fake mockup players were copied', !app.includes('Jaylen Walker') && !app.includes('Marcus Evans') && !app.includes('Ethan Johnson'));
check('Existing play art remains functional', fs.readdirSync(path.join(root,'assets','play-diagrams')).filter(f => f.endsWith('.svg') && f !== 'formation-fallback.svg').length === 48 && RUTGERS_PLAYBOOK.every(p => p.diagramPath && fs.existsSync(path.join(root,p.diagramPath))));
const rankings = engine.buildRankings(ctx(1,5), [], []);
check('Best Call remains functional', rankings.length > 0 && rankings[0].score >= 0);
check('Top 3 remains functional and diverse', engine.diverseTop(rankings, 4).length >= 3 && new Set(engine.diverseTop(rankings, 4).map(p => p.conceptFamily)).size >= 2);
check('Gameplan import validation accepts enriched package', (() => { try { const fn = require(path.join(root,'app.js')); return GAMEPLAN_WEEKLY.package_type === 'gameplan_weekly_update'; } catch { return false; } })());
check('Recruiting import validation accepts enriched package', RECRUITING_WEEKLY.package_type === 'recruiting_weekly_update' && Array.isArray(RECRUITING_WEEKLY.active_board));
check('Invalid imports preserve state by validating before assignment', app.indexOf('validateGameplanWeekly(parsed)') < app.indexOf('window.GAMEPLAN_WEEKLY = parsed') && app.indexOf('validateRecruitingWeekly(parsed)') < app.indexOf('window.RECRUITING_WEEKLY = parsed'));
check('More page contains utilities/history/analytics/settings only', app.includes('Weekly Data') && app.includes('History') && app.includes('Analytics') && app.includes('Settings & Tools') && !app.includes('traitList'));
check('Mobile CSS prevents horizontal overflow and keeps bottom nav fixed', css.includes('overflow-x:hidden') && css.includes('position:fixed') && css.includes('env(safe-area-inset-bottom)'));
check('GitHub Pages relative paths are preserved', index.includes('data/engine_data.js') && !app.includes('fetch(') && !index.includes('http://'));
check('Repeated Not available is avoided in enriched card renderers', (app.match(/Not available/g) || []).length <= 8 && app.includes('cleanValue'));
check('Weekly action plan links board rows to prospect details when available', app.includes('classById') && app.includes('row.prospect_id') && app.includes('prospect.scouting_summary'));
check('Last Game and Season Stats hide missing stat grids cleanly', app.includes('function renderStatSections') && app.includes('No verified ${title.toLowerCase()} stat grid was included'));

const report = ['# VALIDATION_REPORT', '', `Validated: ${new Date().toISOString()}`, '', ...checks.map(c => `- ${c.passed ? 'PASS' : 'FAIL'} - ${c.name}${c.detail ? ` (${c.detail})` : ''}`), '', checks.every(c => c.passed) ? 'Overall: PASS' : 'Overall: FAIL'].join('\n');
fs.writeFileSync(path.join(root, 'VALIDATION_REPORT.md'), report + '\n');
console.log(report);
if (!checks.every(c => c.passed)) process.exit(1);
