const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const context = { window: {}, localStorage: { getItem: () => null, setItem: () => {}, removeItem: () => {} } };
vm.createContext(context);
for (const file of ['data/rutgers_team.js','data/rutgers_playbook.js','data/weekly_plan.js','data/game_history.js','data/recruiting_data.js','data/engine_data.js','data/phase1_verified_data.js','data/player_media.js']) {
  vm.runInContext(fs.readFileSync(path.join(root, file), 'utf8'), context, { filename: file });
}
Object.assign(global, context.window);
global.window = { GAME_HISTORY: [] };
global.localStorage = context.localStorage;
const engine = require(path.join(root, 'app.js'));
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const checks = [];
function check(name, passed, detail = '') { checks.push({ name, passed: Boolean(passed), detail }); }
function ctx(down, yards, zone = 'normal', gameState = 'normal') {
  const dist = yards <= 3 ? 'short' : yards <= 6 ? 'medium' : 'long';
  let key = dist;
  if (zone === 'goal_line' || zone === 'red_zone') key = zone;
  if (gameState === 'two_minute' || gameState === 'must_score') key = gameState;
  if (gameState === 'protect_lead') key = 'short';
  return { down, dist, distanceYards: yards, zone, gameState, key };
}
const requiredFiles = ['rutgers_roster_base.json','rutgers_last_game_stats.json','rutgers_season_stats.json','opponent_last_game_stats.json','opponent_season_stats.json','player_matchups.json','OREGON_PLAYBOOK_VISIBLE_TRANSCRIPT_VERIFIED.json','PHASE1_DATA_PACKAGE_MANIFEST.json','recruiting_class.json','recruiting_weekly.json','team_needs.json','coach_recruiting_modifiers.json','gameplan_weekly.json','APP_DATA_BINDING_REQUIREMENTS.json','base/rutgers_player_media.json','base/player_card_registry.json','weekly/opponent_player_media.json','player_media.js'];
const phase1Transcript = JSON.parse(fs.readFileSync(path.join(root,'data','OREGON_PLAYBOOK_VISIBLE_TRANSCRIPT_VERIFIED.json'), 'utf8'));
const phase1Matchups = JSON.parse(fs.readFileSync(path.join(root,'data','player_matchups.json'), 'utf8'));
const rutgersLast = JSON.parse(fs.readFileSync(path.join(root,'data','rutgers_last_game_stats.json'), 'utf8'));
const rutgersSeason = JSON.parse(fs.readFileSync(path.join(root,'data','rutgers_season_stats.json'), 'utf8'));
const rutgersMedia = JSON.parse(fs.readFileSync(path.join(root,'data','base','rutgers_player_media.json'), 'utf8'));
const opponentMedia = JSON.parse(fs.readFileSync(path.join(root,'data','weekly','opponent_player_media.json'), 'utf8'));
const registry = JSON.parse(fs.readFileSync(path.join(root,'data','base','player_card_registry.json'), 'utf8'));
check('Authoritative Phase 1 JSON files are present', requiredFiles.every(file => fs.existsSync(path.join(root,'data',file))));
check('Shared roster source has 48 verified players', RUTGERS_ROSTER_BASE.players.length === 48 && RUTGERS_ROSTER_BASE.package_type === 'rutgers_roster_base');
check('No duplicate hardcoded roster is used by the visible Recruiting engine', app.includes('function loadRutgersRoster') && app.includes('return sharedRosterBase()'));
check('Gameplan engine reads enriched opponent/profile/player/group/matchup data', app.includes('loadOpponentProfile') && app.includes('loadOpponentPlayers') && app.includes('loadOpponentGroups') && app.includes('loadMatchups'));
check('Recruiting engine reads enriched class, weekly, team needs, and coach modifiers', app.includes('loadRecruitingClass') && app.includes('loadRecruitingWeekly') && app.includes('loadTeamNeeds') && app.includes('COACH_RECRUITING_MODIFIERS'));
check('Gameplan tab structure is present', ['gameMatchupHeader','recommendation','top3Inline','quickSummary','gameDayUsage','gameDayAlerts'].every(token => app.includes(token) || index.includes(token)));
check('Best Call keeps visible play art', app.includes('large-diagram') && app.includes('play.diagramPath'));
check('Top Plays supports required filters', ['run','pass','rpo','pa','screen','rankFormation','rankPersonnel','rankSituation','rankRisk','rankZone','rankState'].every(token => app.includes(token)));
check('Personnel heading and dynamic Rutgers/opponent comparison exist', app.includes('Personnel & Matchups') && app.includes('renderGameMatchupHeader') && app.includes('activeOpponentName()'));
check('Personnel includes run direction map', app.includes('function renderRunDirection') && app.includes('lane-map') && app.includes('Left edge') && app.includes('Right edge'));
check('Run direction map avoids horizontal overflow at phone width', css.includes('grid-template-columns:repeat(auto-fit,minmax(92px,1fr))') && css.includes('overflow-x:hidden'));
check('Personnel includes protection map', app.includes('function renderProtection') && app.includes('pressure-map') && app.includes('Right edge') && app.includes('highestRiskMatchup'));
check('Protection map avoids horizontal overflow at phone width', css.includes('grid-template-columns:repeat(auto-fit,minmax(104px,1fr))'));
check('Personnel includes current opponent accordions', app.includes('function renderOpponent') && app.includes('${activeOpponentName()} Scouting') && app.includes('groupOpponentPlayers') && PURDUE_OPPONENT_PLAYERS.players.length === 16);
check('Personnel includes matchup cards', app.includes('function renderMatchups') && PURDUE_MATCHUPS.matchups.length >= 3);
check('Recruiting overview uses real resources', RECRUITING_WEEKLY.resources.scholarship_limit === 35 && RECRUITING_WEEKLY.resources.weekly_hours_total === 440 && app.includes('scholarships_used'));
check('All recruiting positions are filterable from class data', new Set(RECRUITING_CLASS.prospects.map(p => p.position).filter(Boolean)).size >= 10 && app.includes('filterPosition'));
check('Prospect descriptions display from analysis', RECRUITING_CLASS.prospects.every(p => p.analysis && p.analysis.summary) && app.includes('Scouting summary'));
check('Opponent player descriptions display from ui_analysis', PURDUE_OPPONENT_PLAYERS.players.every(p => p.ui_analysis && p.ui_analysis.summary) && app.includes('ui_analysis'));
check('Matchup descriptions display', PURDUE_MATCHUPS.matchups.every(m => m.description) && app.includes('row.description'));
check('Null fields are hidden in normal UI helpers', app.includes('function maybeRow') && app.includes('return cleaned ?') && !app.includes('Unknown stars'));
check('No Name unverified remains', !index.includes('Name unverified') && !app.includes('Name unverified'));
check('No static opponent facts remain in noscript fallback', !index.includes('Purdue record') && !index.includes('Q. Gillians') && index.includes('Enable JavaScript'));
check('No old four quarterback summary boxes remain', !app.includes('Quarterbacks') || app.indexOf('Quarterbacks') < app.indexOf('function loadRutgersRoster'));
check('No fake mockup players were copied', !app.includes('Jaylen Walker') && !app.includes('Marcus Evans') && !app.includes('Ethan Johnson'));
check('Oregon visible playbook inventory imports every verified row', RUTGERS_PLAYBOOK.length === 192 && phase1Transcript.summary.unique_visible_formation_play_combinations === 192);
check('Oregon playbook completeness is not overstated', phase1Transcript.complete_playbook_status === 'CANNOT_VERIFY_COMPLETE_FROM_THIS_VIDEO' && app.includes('CANNOT_VERIFY_COMPLETE_FROM_THIS_VIDEO') === false);
check('Missing Oregon play art uses placeholders without dropping plays', RUTGERS_PLAYBOOK.every(p => p.diagramPath === 'assets/play-diagrams/formation-fallback.svg' && fs.existsSync(path.join(root,p.diagramPath))));
const rankings = engine.buildRankings(ctx(1,5), [], []);
check('Best Call remains functional', rankings.length > 0 && rankings[0].score >= 0);
check('Top 3 remains functional and diverse', engine.diverseTop(rankings, 4).length >= 3 && new Set(engine.diverseTop(rankings, 4).map(p => p.conceptFamily)).size >= 2);
check('Gameplan import validation accepts enriched package', (() => { try { const fn = require(path.join(root,'app.js')); return GAMEPLAN_WEEKLY.package_type === 'gameplan_weekly_update'; } catch { return false; } })());
check('Recruiting import validation accepts enriched package', RECRUITING_WEEKLY.package_type === 'recruiting_weekly_update' && Array.isArray(RECRUITING_WEEKLY.active_board));
check('Invalid imports preserve state by validating before assignment', app.indexOf('validateGameplanWeekly(parsed)') < app.indexOf('window.GAMEPLAN_WEEKLY = parsed') && app.indexOf('validateRecruitingWeekly(parsed)') < app.indexOf('window.RECRUITING_WEEKLY = parsed'));
check('More page contains utilities/history/analytics/settings only', app.includes('Weekly Data') && app.includes('History') && app.includes('Analytics') && app.includes('Settings & Tools') && !app.includes('traitList'));
check('Mobile CSS prevents horizontal overflow and keeps bottom nav fixed', css.includes('overflow-x:hidden') && css.includes('position:fixed') && css.includes('env(safe-area-inset-bottom)'));
check('GitHub Pages relative paths are preserved', index.includes('data/engine_data.js') && !app.includes('fetch(') && !index.includes('http://'));
check('Repeated Not available is avoided in enriched card renderers', (app.match(/Not available/g) || []).length <= 8 && app.includes('cleanValue'));
check('Weekly action plan links board rows to prospect details when available', app.includes('classById') && app.includes('row.prospect_id') && app.includes('prospect.scouting_summary'));
check('Last Game and Season Stats remain separate with verified files', rutgersLast.package_type === 'rutgers_last_game_stats' && rutgersSeason.package_type === 'rutgers_season_stats' && app.includes('loadRutgersLastGameStats') && app.includes('loadRutgersSeasonStats'));
check('Gameplan default is compact with drill-down details', app.includes('compact-best') && app.includes('View Full Breakdown') && app.includes('View Matchup Detail') && app.includes('alt-strip'));
check('Top Plays uses compact rows and advanced filter drawer', app.includes('compact-play-row') && app.includes('Advanced Filters') && app.includes('sticky-filter'));
check('Personnel uses one internal workspace section at a time', app.includes('function renderPersonnelPanel') && app.includes('active === "overview"') && app.includes('renderStatsWorkspace') && app.includes('renderScoutingReport'));
check('Roster uses horizontal position boxes instead of one long expanded report', app.includes('ROSTER_POSITION_GROUPS') && app.includes('position-rail') && app.includes('showRosterGroup') && css.includes('.position-box'));
check('Matchups show player-vs-player cards where position data resolves', app.includes('findRutgersMatchupPlayer') && app.includes('findOpponentMatchupPlayer') && app.includes('matchup-sides'));
check('Matchups bind to player_matchups.json', phase1Matchups.matchups.length === 7 && app.includes('PLAYER_MATCHUPS') && app.includes('LIMITED DATA'));
check('Recruiting board starts from active_board when present', app.includes('function activeBoardRows') && app.includes('if (board.length)') && app.includes('board_order'));
check('Prospect rating renderer hides unavailable stars and never prints Star as a value', app.includes('function starRating') && app.includes('aria-label="${stars}-star prospect"') && !app.includes('${cleanValue(p.stars)} stars'));
check('Roster and prospects default to tap-open detail rows', app.includes('compact-person') && app.includes('compact-prospect') && app.includes('compact-action'));
check('Run and protection maps use compact tappable cells', app.includes('compact-lane-map') && app.includes('compact-pressure-map'));
check('More tab uses compact accordions for secondary groups', app.includes('details class="utility-section compact-detail"'));
check('Player media static bundle loads before app.js', index.indexOf('data/player_media.js') > index.indexOf('data/phase1_verified_data.js') && index.indexOf('data/player_media.js') < index.indexOf('app.js'));
check('Rutgers portrait registry covers every verified roster player', rutgersMedia.players.length === RUTGERS_ROSTER_BASE.players.length && rutgersMedia.players.every(row => RUTGERS_ROSTER_BASE.players.some(player => player.player_id === row.player_id)));
check('Opponent portrait registry covers every current opponent player', opponentMedia.players.length === PURDUE_OPPONENT_PLAYERS.players.length && opponentMedia.players.every(row => PURDUE_OPPONENT_PLAYERS.players.some(player => player.player_id === row.player_id)));
check('Every portrait asset exists', [...rutgersMedia.players, ...opponentMedia.players].every(row => fs.existsSync(path.join(root, row.portrait_path))));
check('Player card registry binds without duplicated ratings', registry.counts.total_cards === registry.rutgers_cards.length + registry.opponent_cards.length && JSON.stringify(registry).indexOf('"overall"') === -1);
check('Player registry count matches generated card inventory', registry.counts.rutgers_players === 48 && registry.counts.opponent_players === 16 && registry.counts.total_cards === 64);
check('Premium player card engine is present', app.includes('function premiumPlayerCard') && app.includes('Season Stats') && app.includes('Recommended Usage') && app.includes('Expandable Detail'));
check('Portrait media binding is used in player and matchup cards', app.includes('function portraitImg') && app.includes('portrait-match-side') && app.includes('mediaForPlayer'));
check('Matchup cards expose grade, confidence, evidence, recommendation, and portraits', app.includes('displayGrade(row.grade, row.internal_score)') && app.includes('Confidence') && app.includes('Evidence') && app.includes('Recommendation') && app.includes('portraitImg(rutgers'));
check('Executive sticky header compacts on scroll', css.includes('.gameday-header.compact-header') && app.includes('window.scrollY > 48'));
check('Top Plays supports favorites and personnel grouping', app.includes('toggleFavoritePlay') && app.includes('rankPersonnel') && app.includes('Favorites'));
check('Top Plays still binds all 192 verified Oregon combinations', RUTGERS_PLAYBOOK.length === 192 && app.includes('Formation') && app.includes('Personnel'));
check('Recruiting has board and prospect-list workspaces', app.includes('Recruiting Board') && app.includes('Prospect List') && app.includes('prospectPoolRows'));
check('Recruiting details include required status fields without duplicated descriptions', ['National Rank','Interest','Offer','Visit','Commit','Gem/Bust','Recommended Action','AI Summary'].every(token => app.includes(token)) && app.includes('aiSummary !== reason'));
check('O-Line visualization includes run, protection, double-team, and chip-help arrows', app.includes('oline-arrows') && app.includes('run-arrow') && app.includes('protect-arrow') && app.includes('double-arrow') && app.includes('chip-arrow'));
check('Responsive layout keeps new cards within phone viewport', css.includes('.player-card-grid') && css.includes('@media(max-width:420px)') && css.includes('overflow-x:hidden'));
check('JSON parsing for new media files succeeds', rutgersMedia.package_type === 'rutgers_player_media' && opponentMedia.package_type === 'opponent_player_media' && registry.package_type === 'player_card_registry');
check('GitHub Pages compatibility remains static', !app.includes('fetch(') && index.includes('data/player_media.js') && [...rutgersMedia.players, ...opponentMedia.players].every(row => !/^https?:/i.test(row.portrait_path)));

const report = ['# VALIDATION_REPORT', '', `Validated: ${new Date().toISOString()}`, '', ...checks.map(c => `- ${c.passed ? 'PASS' : 'FAIL'} - ${c.name}${c.detail ? ` (${c.detail})` : ''}`), '', checks.every(c => c.passed) ? 'Overall: PASS' : 'Overall: FAIL'].join('\n');
fs.writeFileSync(path.join(root, 'VALIDATION_REPORT.md'), report + '\n');
console.log(report);
if (!checks.every(c => c.passed)) process.exit(1);
