const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const context = { window: {}, localStorage: { getItem: () => null, setItem: () => {}, removeItem: () => {} } };
vm.createContext(context);
for (const file of ['data/rutgers_team.js','data/rutgers_playbook.js','data/weekly_plan.js','data/game_history.js','data/recruiting_data.js','data/engine_data.js','data/phase1_verified_data.js','data/player_media.js','data/card_registry.js','data/weekly/coaching_decisions.js','data/weekly/run_lane_analysis.js','data/weekly/weekly_matchup_summary.js']) {
  vm.runInContext(fs.readFileSync(path.join(root, file), 'utf8'), context, { filename: file });
}
Object.assign(global, context.window);
global.window = { GAME_HISTORY: [] };
global.localStorage = context.localStorage;
const engine = require(path.join(root, 'app.js'));
const index = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const checks = [];
function check(name, passed, detail = '') { checks.push({ name, passed: Boolean(passed), detail }); }
function ctx(down, yards, zone = 'normal', gameState = 'normal') {
  const dist = yards <= 3 ? 'short' : yards <= 6 ? 'medium' : 'long';
  let key = dist;
  if (zone === 'goal_line' || zone === 'red_zone') key = zone;
  if (gameState === 'two_minute' || gameState === 'must_score') key = gameState;
  if (gameState === 'protect_lead') key = 'short';
  return { down, dist, distanceYards: yards, zone, gameState, key };
}
const requiredFiles = ['rutgers_roster_base.json','rutgers_last_game_stats.json','rutgers_season_stats.json','opponent_last_game_stats.json','opponent_season_stats.json','player_matchups.json','OREGON_PLAYBOOK_VISIBLE_TRANSCRIPT_VERIFIED.json','PHASE1_DATA_PACKAGE_MANIFEST.json','recruiting_class.json','recruiting_weekly.json','team_needs.json','coach_recruiting_modifiers.json','gameplan_weekly.json','APP_DATA_BINDING_REQUIREMENTS.json','base/rutgers_player_media.json','base/player_card_registry.json','weekly/opponent_player_media.json','weekly/coaching_decisions.json','weekly/run_lane_analysis.json','weekly/weekly_matchup_summary.json','player_media.js','card_registry.json','card_registry.js'];
const phase1Transcript = JSON.parse(fs.readFileSync(path.join(root,'data','OREGON_PLAYBOOK_VISIBLE_TRANSCRIPT_VERIFIED.json'), 'utf8'));
const phase1Matchups = JSON.parse(fs.readFileSync(path.join(root,'data','player_matchups.json'), 'utf8'));
const cardRegistry = JSON.parse(fs.readFileSync(path.join(root,'data','card_registry.json'), 'utf8'));
const coachingDecisions = JSON.parse(fs.readFileSync(path.join(root,'data','weekly','coaching_decisions.json'), 'utf8'));
const runLaneAnalysis = JSON.parse(fs.readFileSync(path.join(root,'data','weekly','run_lane_analysis.json'), 'utf8'));
const weeklyMatchupSummary = JSON.parse(fs.readFileSync(path.join(root,'data','weekly','weekly_matchup_summary.json'), 'utf8'));
const rutgersLast = JSON.parse(fs.readFileSync(path.join(root,'data','rutgers_last_game_stats.json'), 'utf8'));
const rutgersSeason = JSON.parse(fs.readFileSync(path.join(root,'data','rutgers_season_stats.json'), 'utf8'));
const rutgersMedia = JSON.parse(fs.readFileSync(path.join(root,'data','base','rutgers_player_media.json'), 'utf8'));
const opponentMedia = JSON.parse(fs.readFileSync(path.join(root,'data','weekly','opponent_player_media.json'), 'utf8'));
const registry = JSON.parse(fs.readFileSync(path.join(root,'data','base','player_card_registry.json'), 'utf8'));
check('Authoritative Phase 1 JSON files are present', requiredFiles.every(file => fs.existsSync(path.join(root,'data',file))));
check('PROJECT_SPEC.md exists', fs.existsSync(path.join(root, 'PROJECT_SPEC.md')));
check('Sprint 2 card registry exists', fs.existsSync(path.join(root, 'data', 'card_registry.json')) && cardRegistry.package_type === 'card_registry' && cardRegistry.schema_version === '1.0');
const visibleRegistryCards = (cardRegistry.cards || []).filter(card => card.visible !== false);
const registryIds = visibleRegistryCards.map(card => card.card_id);
check('Card registry schema is valid for visible cards', visibleRegistryCards.every(card => card.card_id && card.card_type && card.tab && card.section && Number.isFinite(Number(card.order)) && ['critical','important','monitor','normal'].includes(card.priority) && ['small','medium','large'].includes(card.size) && typeof card.expandable === 'boolean' && card.source_refs && typeof card.source_refs === 'object'));
check('Visible registry cards have unique card_id values', registryIds.length === new Set(registryIds).size);
check('Visible matchup registry entries resolve to player_matchups.json', visibleRegistryCards.filter(card => card.card_type === 'key_matchup').every(card => phase1Matchups.matchups.some(row => row.matchup_id === card.source_refs.matchup_id)));
check('Card registry does not duplicate player names or ratings', !/"name"\s*:|"overall"\s*:|"internal_score"\s*:|"confidence"\s*:|"grade"\s*:|"recommendation/i.test(JSON.stringify(cardRegistry)));
check('Card registry static bundle is loaded before app.js', index.indexOf('data/card_registry.js') > index.indexOf('data/player_media.js') && index.indexOf('data/card_registry.js') < index.indexOf('app.js'));
check('Shared card engine primitives exist', ['function BaseCard','function CardHeader','function CardSection','function MetricRow','function StatBlock','function Badge','function PortraitBlock','function LimitedDataState','function ExpandableCard','function CardActions'].every(token => app.includes(token)));
check('Central defensive card formatter exists', app.includes('function cardValue') && app.includes('function cleanValue') && app.indexOf('function cleanValue') < app.indexOf('function cardValue'));
check('Card resolver layer exists', ['function loadCardRegistry','function cardRegistryEntries','function resolveCardEntry','function keyMatchupRegistryModels'].every(token => app.includes(token)));
const resolverSource = (app.match(/function resolveCardEntry[\s\S]*?\n}\n\nfunction keyMatchupRegistryModels/) || [''])[0];
check('Card resolver does not mutate authoritative JSON data', !/row\.[A-Za-z0-9_]+\s*=|\b(row|rutgers|opponent)\[[^\]]+\]\s*=/.test(resolverSource));
check('Approved matchup card uses shared card primitives', app.includes('return ExpandableCard({') && app.includes('CardSection("Matchup Edge"') && app.includes('CardHeader({'));
const packBIds = ['dashboard_game_header','dashboard_featured_player','dashboard_biggest_risk','dashboard_best_run_lane','dashboard_protection_call','dashboard_passing_focus','dashboard_red_zone_plan','dashboard_third_down_plan','dashboard_top_matchups_preview','dashboard_alerts','dashboard_tempo','team_card_rutgers','team_card_opponent'];
const cardById = new Map((cardRegistry.cards || []).map(card => [card.card_id, card]));
const dashboardCards = (cardRegistry.cards || []).filter(card => card.visible !== false && card.tab === 'gameplan' && card.section === 'dashboard').sort((a,b) => Number(a.order) - Number(b.order));
check('Pack B registry entries exist', packBIds.every(id => cardById.has(id)));
check('Dashboard order resolves from registry', dashboardCards.map(card => card.card_id).join('|') === ['dashboard_game_header','dashboard_featured_player','dashboard_biggest_risk','dashboard_best_run_lane','dashboard_protection_call','dashboard_passing_focus','dashboard_red_zone_plan','dashboard_third_down_plan','dashboard_top_matchups_preview','dashboard_alerts'].join('|'));
check('Pack B source refs resolve without duplicated football data', packBIds.every(id => cardById.get(id) && cardById.get(id).source_refs && typeof cardById.get(id).source_refs === 'object') && !/"record"\s*:|"overall"\s*:|"offense"\s*:|"defense"\s*:|"recommendation"\s*:|"confidence"\s*:/.test(JSON.stringify(cardRegistry)));
check('Executive dashboard container exists on Gameplan tab', index.includes('id="executiveDashboard"') && app.includes('function renderExecutiveDashboard') && app.includes('dashboardRegistryCards("dashboard")'));
const dashboardHtml = dashboardCards.map(card => engine.renderDashboardCard(card)).join('\n');
check('Executive dashboard renders from registry cards', dashboardHtml.includes('dashboard_game_header') && dashboardHtml.includes('dashboard_featured_player') && dashboardHtml.includes('dashboard_biggest_risk'));
check('Game Header has both teams and verified ratings', dashboardHtml.includes('game-header-card') && dashboardHtml.includes('OVR 84') && dashboardHtml.includes('OFF 84') && dashboardHtml.includes('DEF 86') && dashboardHtml.includes('OVR 64') && dashboardHtml.includes('OFF 64') && dashboardHtml.includes('DEF 64'));
check('Team Cards render Last Game and Season separately', engine.renderDashboardCard(cardById.get('team_card_rutgers')).includes('Last Game') && engine.renderDashboardCard(cardById.get('team_card_rutgers')).includes('Season') && engine.renderDashboardCard(cardById.get('team_card_opponent')).includes('Last Game') && engine.renderDashboardCard(cardById.get('team_card_opponent')).includes('Season'));
check('Featured Player resolves by weekly player identity to roster player_id', (() => { const result = engine.resolveFeaturedPlayer(); return result.player && result.player.player_id && result.weeklyRow && result.weeklyRow.name === result.player.name; })());
check('Biggest Risk resolves by opponent player and matchup ID', (() => { const result = engine.biggestRiskModel(); return result.row && result.row.matchup_id && result.opponent && result.opponent.player_id && result.rutgers; })());
check('Weekly tactical cards read from verified JSON or verified playbook context', ['dashboard_best_run_lane','dashboard_protection_call','dashboard_passing_focus','dashboard_red_zone_plan','dashboard_third_down_plan','dashboard_tempo'].every(id => { const model = engine.tacticalCardModel(cardById.get(id)); return model && model.recommendation && model.title; }));
check('Unsupported tactical cards remain outside the default dashboard', !dashboardCards.some(card => /two_minute|goal_line|screen_constraint/i.test(card.card_id)));
const previewHtml = engine.renderDashboardCard(cardById.get('dashboard_top_matchups_preview'));
check('Top Matchups Preview preserves approved order', engine.orderedMatchupRows().slice(0,3).map(item => item.row.matchup_id).join('|') === 'rt_vs_redg|c_vs_dt|hb2_vs_sam' && previewHtml.indexOf('B. Newberry') < previewHtml.indexOf('D. Sturgis') && previewHtml.indexOf('D. Sturgis') < previewHtml.indexOf('J. Haskins'));
check('Dashboard fixture contains no raw nullish/object text', !/\[object Object\]|undefined|(^|[>\s])null([<\s]|$)/i.test(dashboardHtml));
check('Pack B cards use shared card primitives', ['gameHeaderCard','featuredPlayerCard','biggestRiskCard','tacticalSummaryCard','topMatchupsPreviewCard','alertsCard'].every(fn => app.includes(`function ${fn}`)) && (dashboardHtml.match(/base-card/g) || []).length >= dashboardCards.length);
const packCIds = ['rutgers_player_card','opponent_player_card','oline_player_card','top_play_card','best_call_card','alternative_play_card','recommended_ball_carrier_block','run_lane_recommendation_block'];
check('Pack C registry entries exist', packCIds.every(id => cardById.has(id)));
check('Coaching decision JSON exists and parses', coachingDecisions.package_type === 'weekly_coaching_decisions' && coachingDecisions.schema_version === '1.0');
check('Run-lane analysis JSON exists and parses', runLaneAnalysis.package_type === 'weekly_run_lane_analysis' && Array.isArray(runLaneAnalysis.lanes));
const rosterIds = new Set(RUTGERS_ROSTER_BASE.players.map(p => p.player_id));
const playIds = new Set(RUTGERS_PLAYBOOK.map(p => p.id));
const matchupIds = new Set(phase1Matchups.matchups.map(m => m.matchup_id));
check('All coaching-decision player IDs resolve', Object.values(coachingDecisions.run_personnel).every(row => rosterIds.has(row.primary_player_id) && (!row.secondary_player_id || rosterIds.has(row.secondary_player_id))));
check('Run-lane references resolve and remain limited without fabricated scores', runLaneAnalysis.lanes.every(lane => lane.score === null && lane.status === 'limited_data' && (lane.recommended_play_ids || []).every(id => playIds.has(id)) && (lane.source_matchup_ids || []).every(id => matchupIds.has(id))));
check('All 48 Rutgers locked Player Cards resolve', RUTGERS_ROSTER_BASE.players.length === 48 && RUTGERS_ROSTER_BASE.players.every(player => engine.premiumPlayerCard(player, 'rutgers').includes(`data-player-id="${player.player_id}"`)));
check('All 16 opponent locked Player Cards resolve', PURDUE_OPPONENT_PLAYERS.players.length === 16 && PURDUE_OPPONENT_PLAYERS.players.every(player => engine.premiumPlayerCard(player, 'opponent').includes(`data-player-id="${player.player_id}"`)));
const samplePlayerHtml = engine.premiumPlayerCard(RUTGERS_ROSTER_BASE.players[0], 'rutgers');
check('Season Stats appear before Last Game in Player Card', samplePlayerHtml.indexOf('Season Stats') > -1 && samplePlayerHtml.indexOf('Season Stats') < samplePlayerHtml.indexOf('Last Game'));
check('Top 6 attributes only in default Player Card section', (samplePlayerHtml.match(/Top 6 Position-Relevant Attributes/g) || []).length === 1 && app.includes('lockedAttributeRows(player, 6)'));
check('Missing stats do not hide players', samplePlayerHtml.includes('Limited data') && samplePlayerHtml.includes(RUTGERS_ROSTER_BASE.players[0].name));
check('LT/LG/C/RG/RT all resolve in locked O-line card', ['LT','LG','C','RG','RT'].every(slot => engine.renderOLine ? true : app.includes('LT — LG — C — RG — RT')) && app.includes('locked-oline-slots'));
check('All 192 verified visible Play Cards resolve', RUTGERS_PLAYBOOK.length === 192 && RUTGERS_PLAYBOOK.every((play, i) => engine.lockedPlayCard({...engine.scorePlay(play, ctx(1,5)), ...play}, i + 1).includes(`data-play-id="${play.id}"`)));
const outsidePlay = RUTGERS_PLAYBOOK.find(play => /outside|stretch|sweep|toss|speed option|perimeter|pin|pull/i.test(play.name) || /outside/i.test(engine.conceptFamily(play))) || RUTGERS_PLAYBOOK.find(play => /counter/i.test(play.name));
const insidePlay = RUTGERS_PLAYBOOK.find(play => /inside|duo|power|trap|dive|iso/i.test(play.name) || /inside/i.test(engine.conceptFamily(play)));
check('Run plays resolve a run style', RUTGERS_PLAYBOOK.filter(play => engine.runStyleForPlay(play)).length > 0);
check('Outside concepts resolve to Haskins by current weekly decision data', outsidePlay && engine.runStyleForPlay(outsidePlay) === 'outside' && engine.runPersonnelDecision(outsidePlay).primary.player_id === 'j-haskins-hb');
check('Inside/power concepts resolve to Simonson by current weekly decision data', insidePlay && ['inside','short_yardage','goal_line'].includes(engine.runStyleForPlay(insidePlay)) && engine.runPersonnelDecision(insidePlay).primary.player_id === 't-simonson-hb');
check('Recommended Ball Carrier block is JSON-driven and renderer has no hardcoded back names', engine.ballCarrierBlock(outsidePlay).includes('J. Haskins') && engine.ballCarrierBlock(insidePlay).includes('T. Simonson') && !/function lockedPlayCard[\s\S]*J\. Haskins|function lockedPlayCard[\s\S]*T\. Simonson/.test(app));
check('Best-side recommendation stays hidden when lane scoring is limited', !engine.bestVerifiedRunLane(insidePlay) && engine.runLaneBlock(insidePlay).includes('Limited data') && !engine.runLaneBlock(insidePlay).includes('Recommended Side</h4><div class="metric-row"><span>Lane</span>'));
check('No internal score mislabeled as lane advantage', !JSON.stringify(runLaneAnalysis).includes('internal_score') && !engine.runLaneBlock(insidePlay).includes('ADVANTAGE'));
const packDIds = ['offensive_executive_summary','offensive_comparison_table','best_play_hero','top_three_selector','run_game_card','passing_game_card','protection_card','offensive_alerts_card','defensive_executive_summary','defensive_comparison_table','biggest_threat_card','pressure_card','coverage_card','defensive_alerts_card'];
check('Pack D registry entries exist', packDIds.every(id => cardById.has(id)));
check('Weekly matchup summary exists and parses', weeklyMatchupSummary.package_type === 'weekly_matchup_summary' && weeklyMatchupSummary.schema_version === '1.0');
const summarySections = ['offense_vs_defense','defense_vs_offense','best_play','top_three','run_game','passing_game','protection','pressure','coverage','alerts','featured_player','biggest_threat'];
check('Weekly matchup summary has required sections', summarySections.every(key => key in weeklyMatchupSummary));
check('Offensive comparison rows resolve from summary', Array.isArray(weeklyMatchupSummary.offense_vs_defense.comparisons) && weeklyMatchupSummary.offense_vs_defense.comparisons.length >= 17 && weeklyMatchupSummary.offense_vs_defense.comparisons.every(row => 'rutgers_value' in row && 'opponent_value' in row && 'reason' in row));
check('Defensive comparison rows resolve from summary', Array.isArray(weeklyMatchupSummary.defense_vs_offense.comparisons) && weeklyMatchupSummary.defense_vs_offense.comparisons.length >= 9 && weeklyMatchupSummary.defense_vs_offense.comparisons.every(row => 'mine_value' in row && 'theirs_value' in row && 'reason' in row));
check('Best Play and Top Three resolve to verified play IDs', playIds.has(weeklyMatchupSummary.best_play.play_id) && weeklyMatchupSummary.top_three.length === 3 && weeklyMatchupSummary.top_three.every(row => playIds.has(row.play_id)));
check('Run Game, Passing Game, Protection, Pressure, Coverage, Alerts resolve', weeklyMatchupSummary.run_game && weeklyMatchupSummary.passing_game && Array.isArray(weeklyMatchupSummary.protection.slots) && weeklyMatchupSummary.pressure && weeklyMatchupSummary.coverage && weeklyMatchupSummary.alerts);
check('Featured Player and Biggest Threat resolve', rosterIds.has(weeklyMatchupSummary.featured_player.player_id) && PURDUE_OPPONENT_PLAYERS.players.some(p => p.player_id === weeklyMatchupSummary.biggest_threat.player_id) && matchupIds.has(weeklyMatchupSummary.biggest_threat.matchup_id));
const coordinatorHtml = engine.renderCoordinatorDashboard();
check('Gameplan is transformed into offensive and defensive coordinator sections', coordinatorHtml.includes('Offensive Gameplan') && coordinatorHtml.includes('Defensive Gameplan') && app.includes('renderCoordinatorDashboard()'));
const topPlayInventory = engine.topPlayInventory();
const topPlayHeroHtml = engine.topPlayHeroCard('best');
const topThreeHeroHtml = engine.topPlayHeroCard('top3');
const topPlayModeSource = (app.match(/function setTopPlaysMode[\s\S]*?\n}/) || [''])[0];
check('Top Plays owns Best Play hero with play art and mode controls', topPlayHeroHtml.includes('data-top-plays-hero') && topPlayHeroHtml.includes('top-play-hero-art') && topPlayHeroHtml.includes('class="active" data-top-play-control="best"') && topPlayHeroHtml.includes('data-top-play-control="top3"') && topPlayHeroHtml.includes(topPlayInventory[0].id));
check('Top Plays owns Top 3 selector without refresh or navigation', topThreeHeroHtml.includes('data-top-three-selector') && (topThreeHeroHtml.match(/data-top-three-row=/g) || []).length === 3 && app.includes('function setTopPlaysMode') && !/location\.href|window\.location/.test(topPlayModeSource));
check('Top Plays inventory reaches all 192 verified Oregon play combinations', topPlayInventory.length === 192 && new Set(topPlayInventory.map(play => play.id)).size === 192);
check('Gameplan no longer renders Top Plays hero, selector, or full play library', !coordinatorHtml.includes('data-top-plays-hero') && !coordinatorHtml.includes('top-three-selector') && !coordinatorHtml.includes('locked-play-card'));
check('Gameplan removes raw Rutgers Offense vs Opponent Defense comparison wall', !coordinatorHtml.includes('Rutgers Offense vs Opponent Defense') && !coordinatorHtml.includes('offense-comparison-table'));
check('Gameplan removes raw Rutgers Defense vs Opponent Offense comparison wall', !coordinatorHtml.includes('Rutgers Defense vs Opponent Offense') && !coordinatorHtml.includes('defense-comparison-table'));
check('Gameplan concise card order resolves', (() => {
  const orderTokens = ['offensive-gameplan','coordinator-run-card','coordinator-pass-card','coordinator-protection-card','defensive-summary-card','coordinator-threat-card','coordinator-pressure-card','coordinator-coverage-card','coordinator-alerts-card'];
  const positions = orderTokens.map(token => coordinatorHtml.indexOf(token));
  return positions.every(pos => pos >= 0) && positions.every((pos, i) => i === 0 || pos > positions[i - 1]);
})());
check('Coordinator dashboard contains no raw nullish/object text', !/\[object Object\]|undefined|(^|[>\s])null([<\s]|$)/i.test(coordinatorHtml));
check('Weekly matchup summary does not duplicate card registry football data', !JSON.stringify(cardRegistry).includes('offensive_matchup_grade') && !JSON.stringify(cardRegistry).includes('biggest_offensive_advantage'));
check('Weekly matchup summary static bundle loads before app.js', index.indexOf('data/weekly/weekly_matchup_summary.js') > index.indexOf('data/weekly/run_lane_analysis.js') && index.indexOf('data/weekly/weekly_matchup_summary.js') < index.indexOf('app.js'));
check('Card registry moves Best Play and Top Three ownership to Top Plays', cardById.get('best_play_hero').tab === 'topplays' && cardById.get('top_three_selector').tab === 'topplays');
check('Card registry hides raw comparison walls from Gameplan', cardById.get('offensive_comparison_table').visible === false && cardById.get('defensive_comparison_table').visible === false);
check('Card registry registers reusable RecruitCard collection', cardById.get('recruit_card_collection') && cardById.get('recruit_card_collection').tab === 'recruiting' && cardById.get('recruit_card_collection').display_variant === 'recruit_card_collection');
check('Shared roster source has 48 verified players', RUTGERS_ROSTER_BASE.players.length === 48 && RUTGERS_ROSTER_BASE.package_type === 'rutgers_roster_base');
check('No duplicate hardcoded roster is used by the visible Recruiting engine', app.includes('function loadRutgersRoster') && app.includes('return sharedRosterBase()'));
check('Gameplan engine reads enriched opponent/profile/player/group/matchup data', app.includes('loadOpponentProfile') && app.includes('loadOpponentPlayers') && app.includes('loadOpponentGroups') && app.includes('loadMatchups'));
check('Recruiting engine reads enriched class, weekly, team needs, and coach modifiers', app.includes('loadRecruitingClass') && app.includes('loadRecruitingWeekly') && app.includes('loadTeamNeeds') && app.includes('COACH_RECRUITING_MODIFIERS'));
check('Gameplan tab structure is present', app.includes('renderCoordinatorDashboard') && app.includes('offensive-gameplan') && app.includes('defensive-gameplan'));
check('Best Call keeps visible play art', app.includes('large-diagram') && app.includes('play.diagramPath'));
check('Top Plays supports required filters', ['run','pass','rpo','pa','screen','rankFormation','rankPersonnel','rankSituation','rankRisk','rankZone','rankState'].every(token => app.includes(token)));
check('Personnel heading and dynamic Rutgers/opponent comparison exist', app.includes('Personnel & Matchups') && app.includes('renderGameMatchupHeader') && app.includes('activeOpponentName()'));
check('Personnel includes run direction map', app.includes('function renderRunDirection') && app.includes('lane-map') && app.includes('Left edge') && app.includes('Right edge'));
check('Run direction map avoids horizontal overflow at phone width', css.includes('grid-template-columns:repeat(auto-fit,minmax(92px,1fr))') && css.includes('overflow-x:hidden'));
check('Personnel includes protection map', app.includes('function renderProtection') && app.includes('pressure-map') && app.includes('Right edge') && app.includes('highestRiskMatchup'));
check('Protection map avoids horizontal overflow at phone width', css.includes('grid-template-columns:repeat(auto-fit,minmax(104px,1fr))'));
check('Personnel includes current opponent accordions', app.includes('function renderOpponent') && app.includes('${activeOpponentName()} Scouting') && app.includes('groupOpponentPlayers') && PURDUE_OPPONENT_PLAYERS.players.length === 16);
check('Personnel includes matchup cards', app.includes('function renderMatchups') && PURDUE_MATCHUPS.matchups.length >= 3);
check('Recruiting overview uses real resources', RECRUITING_WEEKLY.resources.scholarship_limit === 35 && RECRUITING_WEEKLY.resources.weekly_hours_total === 440 && app.includes('scholarships_used'));
check('All recruiting positions are filterable from class data', new Set(RECRUITING_CLASS.prospects.map(p => p.position).filter(Boolean)).size >= 10 && app.includes('filterPosition'));
check('Prospect descriptions display from analysis', RECRUITING_CLASS.prospects.every(p => p.analysis && p.analysis.summary) && app.includes('Scouting summary'));
check('Opponent player descriptions display from ui_analysis', PURDUE_OPPONENT_PLAYERS.players.every(p => p.ui_analysis && p.ui_analysis.summary) && app.includes('ui_analysis'));
check('Matchup descriptions display', PURDUE_MATCHUPS.matchups.every(m => m.description) && app.includes('row.description'));
check('Null fields are hidden in normal UI helpers', app.includes('function maybeRow') && app.includes('formatLimited') && !app.includes('Unknown stars'));
check('No Name unverified remains', !index.includes('Name unverified') && !app.includes('Name unverified'));
check('No static opponent facts remain in noscript fallback', !index.includes('Purdue record') && !index.includes('Q. Gillians') && index.includes('Enable JavaScript'));
check('No old four quarterback summary boxes remain', !app.includes('Quarterbacks') || app.indexOf('Quarterbacks') < app.indexOf('function loadRutgersRoster'));
check('No fake mockup players were copied', !app.includes('Jaylen Walker') && !app.includes('Marcus Evans') && !app.includes('Ethan Johnson'));
check('Oregon visible playbook inventory imports every verified row', RUTGERS_PLAYBOOK.length === 192 && phase1Transcript.summary.unique_visible_formation_play_combinations === 192);
check('Oregon playbook completeness is not overstated', phase1Transcript.complete_playbook_status === 'CANNOT_VERIFY_COMPLETE_FROM_THIS_VIDEO' && app.includes('CANNOT_VERIFY_COMPLETE_FROM_THIS_VIDEO') === false);
check('Missing Oregon play art uses placeholders without dropping plays', RUTGERS_PLAYBOOK.every(p => p.diagramPath === 'assets/play-diagrams/formation-fallback.svg' && fs.existsSync(path.join(root,p.diagramPath))));
const rankings = engine.buildRankings(ctx(1,5), [], []);
check('Best Call remains functional', rankings.length > 0 && rankings[0].score >= 0);
check('Top 3 remains functional and diverse', engine.diverseTop(rankings, 4).length >= 3 && new Set(engine.diverseTop(rankings, 4).map(p => p.conceptFamily)).size >= 2);
check('Gameplan import validation accepts enriched package', (() => { try { const fn = require(path.join(root,'app.js')); return GAMEPLAN_WEEKLY.package_type === 'gameplan_weekly_update'; } catch { return false; } })());
check('Recruiting import validation accepts enriched package', RECRUITING_WEEKLY.package_type === 'recruiting_weekly_update' && Array.isArray(RECRUITING_WEEKLY.active_board));
check('Invalid imports preserve state by validating before assignment', app.indexOf('validateGameplanWeekly(parsed)') < app.indexOf('window.GAMEPLAN_WEEKLY = parsed') && app.indexOf('validateRecruitingWeekly(parsed)') < app.indexOf('window.RECRUITING_WEEKLY = parsed'));
check('More page contains utilities/history/analytics/settings only', app.includes('Weekly Data') && app.includes('History') && app.includes('Analytics') && app.includes('Settings & Tools') && !app.includes('traitList'));
check('Mobile CSS prevents horizontal overflow and keeps bottom nav fixed', css.includes('overflow-x:hidden') && css.includes('position:fixed') && css.includes('env(safe-area-inset-bottom)'));
check('GitHub Pages relative paths are preserved', index.includes('data/engine_data.js') && !app.includes('fetch(') && !index.includes('http://'));
check('Repeated Not available is avoided in enriched card renderers', (app.match(/Not available/g) || []).length <= 8 && app.includes('cleanValue'));
const firstBoardRow = (RECRUITING_WEEKLY.active_board || [])[0] || {};
const firstProspect = (RECRUITING_CLASS.prospects || []).find(prospect => prospect.prospect_id === firstBoardRow.prospect_id) || {};
const recruitFixtureHtml = engine.RecruitCard({ ...firstBoardRow, prospect: firstProspect }, 0, 'board');
check('Weekly action plan renders through reusable RecruitCard records', app.includes('classById') && app.includes('row.prospect_id') && app.includes('RecruitCard({ ...row, prospect }') && recruitFixtureHtml.includes('data-recruit-card'));
check('RecruitCard scheme fit values are restricted to approved labels', ['Strong fit','Moderate fit','Weak fit','Insufficient verified data'].every(value => engine.resolvedSchemeFit(value) === value) && engine.resolvedSchemeFit('unknown') === 'Insufficient verified data');
check('RecruitCard avoids generic evaluate/prioritize/assess instructions', !/Review against roster need|Evaluate how|Prioritize if|Assess whether/i.test(recruitFixtureHtml));
check('Last Game and Season Stats remain separate with verified files', rutgersLast.package_type === 'rutgers_last_game_stats' && rutgersSeason.package_type === 'rutgers_season_stats' && app.includes('loadRutgersLastGameStats') && app.includes('loadRutgersSeasonStats'));
check('Gameplan default is compact with drill-down details', app.includes('compact-best') && app.includes('View Full Breakdown') && app.includes('View Matchup Detail') && app.includes('alt-strip'));
check('Top Plays uses compact rows and advanced filter drawer', app.includes('compact-play-row') && app.includes('Advanced Filters') && app.includes('sticky-filter'));
check('Personnel uses one internal workspace section at a time', app.includes('function renderPersonnelPanel') && app.includes('active === "overview"') && app.includes('renderStatsWorkspace') && app.includes('renderScoutingReport'));
check('Roster uses horizontal position boxes instead of one long expanded report', app.includes('ROSTER_POSITION_GROUPS') && app.includes('position-rail') && app.includes('showRosterGroup') && css.includes('.position-box'));
check('Matchups show player-vs-player cards where position data resolves', app.includes('findRutgersMatchupPlayer') && app.includes('findOpponentMatchupPlayer') && app.includes('broadcast-matchup-grid'));
check('Matchups bind to player_matchups.json', phase1Matchups.matchups.length === 7 && app.includes('PLAYER_MATCHUPS') && app.includes('Limited data'));
check('Recruiting board starts from active_board when present', app.includes('function activeBoardRows') && app.includes('if (board.length)') && app.includes('board_order'));
check('Prospect rating renderer hides unavailable stars and never prints Star as a value', app.includes('function starRating') && app.includes('aria-label="${stars}-star prospect"') && !app.includes('${cleanValue(p.stars)} stars'));
check('Roster and prospects default to tap-open detail rows', app.includes('compact-person') && app.includes('compact-prospect') && app.includes('compact-action'));
check('Run and protection maps use compact tappable cells', app.includes('compact-lane-map') && app.includes('compact-pressure-map'));
check('More tab uses compact accordions for secondary groups', app.includes('details class="utility-section compact-detail"'));
check('Player media static bundle loads before app.js', index.indexOf('data/player_media.js') > index.indexOf('data/phase1_verified_data.js') && index.indexOf('data/player_media.js') < index.indexOf('app.js'));
check('Rutgers portrait registry covers every verified roster player', rutgersMedia.players.length === RUTGERS_ROSTER_BASE.players.length && rutgersMedia.players.every(row => RUTGERS_ROSTER_BASE.players.some(player => player.player_id === row.player_id)));
check('Opponent portrait registry covers every current opponent player', opponentMedia.players.length === PURDUE_OPPONENT_PLAYERS.players.length && opponentMedia.players.every(row => PURDUE_OPPONENT_PLAYERS.players.some(player => player.player_id === row.player_id)));
check('Every portrait asset exists', [...rutgersMedia.players, ...opponentMedia.players].every(row => fs.existsSync(path.join(root, row.portrait_path))));
check('Player card registry binds without duplicated ratings', registry.counts.total_cards === registry.rutgers_cards.length + registry.opponent_cards.length && JSON.stringify(registry).indexOf('"overall"') === -1);
check('Player registry count matches generated card inventory', registry.counts.rutgers_players === 48 && registry.counts.opponent_players === 16 && registry.counts.total_cards === 64);
check('Premium player card engine is present', app.includes('function premiumPlayerCard') && app.includes('Season Stats') && app.includes('Weekly Role') && app.includes('More Detail'));
check('Portrait media binding is used in player and matchup cards', app.includes('function portraitImg') && app.includes('broadcast-player') && app.includes('mediaForPlayer'));
check('Matchup cards expose grade, confidence, evidence, recommendation, and portraits', app.includes('displayGrade(row.grade, row.internal_score)') && app.includes('Confidence') && app.includes('Evidence') && app.includes('Tactical Recommendation') && app.includes('portraitImg(rutgers'));
check('Executive sticky header compacts on scroll', css.includes('.gameday-header.compact-header') && app.includes('window.scrollY > 48'));
check('Top Plays supports favorites and personnel grouping', app.includes('toggleFavoritePlay') && app.includes('rankPersonnel') && app.includes('Favorites'));
check('Top Plays still binds all 192 verified Oregon combinations', RUTGERS_PLAYBOOK.length === 192 && app.includes('Formation') && app.includes('Personnel'));
check('Recruiting has board and prospect-list workspaces', app.includes('Recruiting Board') && app.includes('Prospect List') && app.includes('prospectPoolRows'));
check('Recruiting details include required status fields without duplicated descriptions', ['National Rank','Interest','Offer','Visit','Commit','Gem/Bust','Recommended Action','AI Summary'].every(token => app.includes(token)) && app.includes('aiSummary !== reason'));
check('O-Line visualization includes run, protection, double-team, and chip-help arrows', app.includes('oline-arrows') && app.includes('run-arrow') && app.includes('protect-arrow') && app.includes('double-arrow') && app.includes('chip-arrow'));
check('Responsive layout keeps new cards within phone viewport', css.includes('.player-card-grid') && css.includes('@media(max-width:420px)') && css.includes('overflow-x:hidden'));
check('JSON parsing for new media files succeeds', rutgersMedia.package_type === 'rutgers_player_media' && opponentMedia.package_type === 'opponent_player_media' && registry.package_type === 'player_card_registry');
check('GitHub Pages compatibility remains static', !app.includes('fetch(') && index.includes('data/player_media.js') && [...rutgersMedia.players, ...opponentMedia.players].every(row => !/^https?:/i.test(row.portrait_path)));
const fixtureHtml = [
  engine.premiumPlayerCard(RUTGERS_ROSTER_BASE.players[0], 'rutgers'),
  engine.opponentPlayerCard(PURDUE_OPPONENT_PLAYERS.players[0]),
  engine.matchupRow(PURDUE_MATCHUPS.matchups[0]),
  engine.renderPersonnelOverview(),
  engine.cleanValue({ name: 'Fixture', stats: { yards: 12, td: 1 }, tags: ['inside', 'zone'] })
].join('\n');
check('Rendered fixtures never leak raw object coercion', !/\[object Object\]|undefined|(^|[>\s])null([<\s]|$)/i.test(fixtureHtml));
check('Nested formatter converts objects to readable labels', engine.cleanValue({ player: 'Q. Gillians', threat_type: 'Power rush', lane: 'right edge' }).includes('Player: Q. Gillians') && !engine.cleanValue({ a: { b: 1 } }).includes('[object Object]'));
check('Player cards render Last Game and Season as separate sections', fixtureHtml.includes('Last Game') && fixtureHtml.includes('Season') && fixtureHtml.includes('mini-stat-block'));
check('Matchup cards use mobile header, comparison, production, and result sections', fixtureHtml.includes('broadcast-matchup-grid') && fixtureHtml.includes('comparison-table') && fixtureHtml.includes('match-production') && fixtureHtml.includes('tactical-callout'));
check('Featured Player and Biggest Risk render as actionable summaries', fixtureHtml.includes('summary-player-card') && fixtureHtml.includes('risk-link') && !fixtureHtml.includes('[object Object]'));
const renderedRecruitDescriptions = (RECRUITING_WEEKLY.active_board || []).map(row => {
  const prospect = (RECRUITING_CLASS.prospects || []).find(p => p.prospect_id === row.prospect_id) || {};
  const a = prospect.analysis || {};
  const values = [row.description, a.recommended_action_reason, prospect.scouting_summary, a.summary].map(value => engine.cleanValue(value)).filter(Boolean);
  return values.find(text => !/active board target|match to the full recruiting-class record requires confirmation|review against roster need|verified scouting profile/i.test(text)) || '';
}).filter(Boolean);
const descriptionCounts = renderedRecruitDescriptions.reduce((acc, text) => (acc[text] = (acc[text] || 0) + 1, acc), {});
check('Repeated generic recruiting descriptions are removed from rendered candidates', !app.includes('Review against roster need and verified scouting profile') && Object.values(descriptionCounts).every(count => count <= 3));
check('Mobile breakpoints 390x844 and 430x932 are covered by responsive CSS', css.includes('@media(max-width:420px)') && css.includes('overflow-x:hidden') && css.includes('env(safe-area-inset-bottom)') && css.includes('env(safe-area-inset-top)'));
check('Only one matchup detail accordion is allowed open per list', app.includes('.compact-match') && app.includes('details.compact-detail[open],details.player-detail[open],details.compact-prospect[open],details.compact-match[open]'));
const orderedMatchups = engine.orderedMatchupRows();
const matchupSystemHtml = engine.renderMatchups();
const keyCardCount = (matchupSystemHtml.match(/data-matchup-id=/g) || []).length - (matchupSystemHtml.includes('allMatchupsPanel') ? (orderedMatchups.length - Math.min(3, orderedMatchups.length)) : 0);
const topThreeIds = orderedMatchups.slice(0, 3).map(item => item.row.matchup_id);
const playerNamesInMatchups = PURDUE_MATCHUPS.matchups.flatMap(row => [row.rutgers_player && row.rutgers_player.name, row.opponent_player && row.opponent_player.name]).filter(Boolean);
check('Reusable MatchupCard component renders key matchup cards', app.includes('function MatchupCard(') && matchupSystemHtml.includes('matchup-card-system') && matchupSystemHtml.includes('priority-badge'));
check('Exactly three valid Key Matchups render when at least three valid rows exist', orderedMatchups.length < 3 ? keyCardCount === orderedMatchups.length : keyCardCount === 3, `key=${keyCardCount}, valid=${orderedMatchups.length}`);
check('Top three matchup cards come from player_matchups.json', topThreeIds.length === Math.min(3, orderedMatchups.length) && topThreeIds.every(id => phase1Matchups.matchups.some(row => row.matchup_id === id)));
check('Top three matchup selection is ordered by priority, confidence, importance, then source order', topThreeIds.join('|') === orderedMatchups.slice(0, 3).map(item => item.row.matchup_id).join('|'));
check('No matchup player names are hardcoded in rendering source', playerNamesInMatchups.every(name => !app.includes(name)));
check('All valid matchup Rutgers and opponent IDs resolve', orderedMatchups.length === phase1Matchups.matchups.filter(row => row.rutgers_player && row.opponent_player).length && orderedMatchups.every(item => item.rutgers && item.opponent));
check('Matchup media paths resolve for valid cards', orderedMatchups.every(item => {
  const rutgersMediaRow = rutgersMedia.players.find(row => row.player_id === item.rutgers.player_id);
  const opponentMediaRow = opponentMedia.players.find(row => row.player_id === item.opponent.player_id);
  return rutgersMediaRow && opponentMediaRow && fs.existsSync(path.join(root, rutgersMediaRow.portrait_path)) && fs.existsSync(path.join(root, opponentMediaRow.portrait_path));
}));
check('Matchup component keeps Last Game and Season separate', matchupSystemHtml.includes('Rutgers Last Game') && matchupSystemHtml.includes('Rutgers Season') && matchupSystemHtml.includes('Opponent Last Game') && matchupSystemHtml.includes('Opponent Season'));
check('Matchup card fixtures contain no raw nullish/object text', !/\[object Object\]|undefined|(^|[>\s])null([<\s]|$)/i.test(matchupSystemHtml));
check('Glossy matchup card styling and mobile overflow safeguards exist', css.includes('.matchup-card') && css.includes('linear-gradient') && css.includes('.matchup-action-row') && css.includes('@media(max-width:420px)') && css.includes('overflow-x:hidden'));
check('Fixed bottom navigation remains visible for matchup card system', css.includes('.bottom-nav') && css.includes('position:fixed') && css.includes('env(safe-area-inset-bottom)'));
const firstMatchupCardHtml = engine.MatchupCard(orderedMatchups[0].row, orderedMatchups[0].rutgers, orderedMatchups[0].opponent);
const defaultMetricCount = (firstMatchupCardHtml.match(/default-metric/g) || []).length;
check('Broadcast matchup visual hierarchy is present', firstMatchupCardHtml.includes('broadcast-matchup-grid') && firstMatchupCardHtml.includes('broadcast-player') && firstMatchupCardHtml.includes('broadcast-vs'));
check('Central matchup-edge panel is dominant and populated', firstMatchupCardHtml.includes('broadcast-edge') && firstMatchupCardHtml.includes('Matchup Edge') && firstMatchupCardHtml.includes('Grade'));
check('Default comparison uses no more than four selected metrics', defaultMetricCount > 0 && defaultMetricCount <= 4, `defaultMetrics=${defaultMetricCount}`);
check('Remaining matchup attributes move to More Detail', firstMatchupCardHtml.includes('more-matchup-detail') && firstMatchupCardHtml.includes('More Detail'));
check('Tactical recommendation renders as primary coaching callout', firstMatchupCardHtml.includes('tactical-callout') && firstMatchupCardHtml.includes('Tactical Recommendation'));
check('Empty production sections collapse to compact Limited data cards', firstMatchupCardHtml.includes('production-card') && firstMatchupCardHtml.includes('limited-production'));
check('Broadcast matchup visual polish CSS exists', css.includes('.broadcast-matchup-grid') && css.includes('.broadcast-edge') && css.includes('.tactical-callout') && css.includes('.player-portrait.broadcast'));
const firstInternalScore = String(orderedMatchups[0].row.internal_score);
const edgePanelMatch = firstMatchupCardHtml.match(/<section class="matchup-edge broadcast-edge">([\s\S]*?)<\/section>/);
const edgePanelHtml = edgePanelMatch ? edgePanelMatch[1] : '';
check('Internal score is not rendered under MATCHUP EDGE', firstInternalScore && !edgePanelHtml.includes(firstInternalScore), `internal=${firstInternalScore}`);
check('Verified differential renders only when explicitly available', engine.matchupEdgeDisplay({ advantage: 'Rutgers', grade: 'B', confidence: 90, verified_edge_differential: 7, internal_score: 88 }).title === 'RUTGERS +7');
check('Advantage-only matchup edge renders without fabricated number', engine.matchupEdgeDisplay({ advantage: 'Purdue', grade: 'D', confidence: 92, internal_score: 68.8 }).title === 'PURDUE ADVANTAGE');
check('Even matchup edge renders without fabricated number', engine.matchupEdgeDisplay({ advantage: 'Even', grade: 'C', confidence: 92, internal_score: 74.6 }).title === 'EVEN');
check('Limited matchup edge state renders correctly', engine.matchupEdgeDisplay({ grade: 'C', confidence: 70, internal_score: 74.6 }).title === 'LIMITED DATA');
const evidenceHtml = engine.evidenceRowsHtml(orderedMatchups[0].row.evidence || []);
check('Evidence renders as separate rows without serialized objects', evidenceHtml.includes('evidence-row-list') && evidenceHtml.includes('evidence-row') && !/\[object Object\]|undefined|(^|[>\s])null([<\s]|$)/i.test(evidenceHtml));
check('Top-three order remains semantic-correction unchanged', topThreeIds.join('|') === 'rt_vs_redg|c_vs_dt|hb2_vs_sam');
const sprint25Docs = ['DESIGN_SYSTEM.md','JSON_STANDARD.md','UI_COMPONENT_STANDARD.md','VALIDATION_STANDARD.md','RELEASE_STANDARD.md'];
const screenshotPages = ['gameplan','personnel','topplays','matchups','recruiting'];
check('Sprint 2.5 design governance docs exist', sprint25Docs.every(file => fs.existsSync(path.join(root, 'docs', file))));
check('Design System Governance Standard is indexed from PROJECT_SPEC', fs.readFileSync(path.join(root, 'PROJECT_SPEC.md'), 'utf8').includes('Design System Governance Standard') && fs.readFileSync(path.join(root, 'PROJECT_SPEC.md'), 'utf8').includes('docs/DESIGN_SYSTEM.md'));
check('Native UI design tokens are present', ['--ds-space-1','--ds-radius-lg','--ds-rutgers','--ds-opponent','--ds-glass','--ds-shadow','--ds-text-hero'].every(token => css.includes(token)));
check('Premium background and glass card system are present', css.includes('.native-backdrop') && css.includes('backdrop-filter') && css.includes('--ds-glass') && css.includes('.panel:before'));
check('Premium floating bottom navigation is present', css.includes('.bottom-nav') && css.includes('border-radius:22px') && css.includes('backdrop-filter:blur(24px)'));
check('Native page transitions and reduced-motion fallback are present', css.includes('@keyframes tabEnter') && css.includes('prefers-reduced-motion') && app.includes('tabScrollPositions'));
check('PWA manifest and app icon are wired for GitHub Pages', fs.existsSync(path.join(root, 'manifest.webmanifest')) && fs.existsSync(path.join(root, 'assets', 'app-icon.svg')) && index.includes('rel="manifest"') && index.includes('apple-touch-icon'));
check('Before screenshots exist for key pages', screenshotPages.every(page => fs.existsSync(path.join(root, 'screenshots', 'sprint2_5_before', `${page}_390x844.png`))));
check('After screenshots exist for key pages', screenshotPages.every(page => fs.existsSync(path.join(root, 'screenshots', 'sprint2_5_after', `${page}_390x844.png`))));
check('Sprint 2.5 screenshot artifacts are non-empty PNG files', ['sprint2_5_before','sprint2_5_after'].every(dir => screenshotPages.every(page => fs.statSync(path.join(root, 'screenshots', dir, `${page}_390x844.png`)).size > 10000)));

const report = ['# VALIDATION_REPORT', '', `Validated: ${new Date().toISOString()}`, '', ...checks.map(c => `- ${c.passed ? 'PASS' : 'FAIL'} - ${c.name}${c.detail ? ` (${c.detail})` : ''}`), '', checks.every(c => c.passed) ? 'Overall: PASS' : 'Overall: FAIL'].join('\n');
fs.writeFileSync(path.join(root, 'VALIDATION_REPORT.md'), report + '\n');
console.log(report);
if (!checks.every(c => c.passed)) process.exit(1);
